# Generated by Django 4.2.16 on 2024-10-13 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('pnune_number', models.CharField(max_length=15)),
                ('number_of_guests', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('special_occasions', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
